import {
  User, Users, Baby, Crown, UserCheck, PersonStanding, Footprints,
  Laugh, Smile, Frown, Meh, ThumbsUp, ThumbsDown, HandMetal,
  Heart, HeartCrack, HeartHandshake,
  MapPin, Map, Navigation, Home, Building2, Castle, Hotel, Factory, Globe, Globe2, Landmark, Mountain, TreePine, Tent, Warehouse,
  Clock, Watch, Calendar, CalendarDays, CalendarClock, Timer, Hourglass,
  Star, Sparkle, Sparkles, Flag, Bookmark, Trophy, Award, Medal, Ribbon, PartyPopper, Zap, Flame,
  Swords, Sword, Shield, Bomb, Target, Crosshair, Skull, Anchor,
  Vote, Scale, Gavel, ScrollText, Stamp, Handshake, Lock, Unlock, Key, KeyRound,
  Church, Cross, Scroll, BookOpen,
  Atom, Microscope, FlaskConical, TestTube, Dna, Telescope, Compass, Cpu, Lightbulb, Sigma, Pi, Infinity as InfinityIcon,
  Monitor, Tv, Tv2, Smartphone, Laptop, Keyboard, Mouse, Wifi, Bluetooth, Signal,
  GraduationCap, School, Library, Pencil,
  Music, Music2, AudioLines, Headphones, Mic, Mic2, Film, Clapperboard, Camera, Ticket, Theater, Drama, Palette, Brush, PenLine, Feather, Book, BookMarked, FileText,
  Gamepad, Gamepad2, Joystick, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6,
  Car, Truck, Bus, Bike, Train, Plane, Rocket, Ship, Sailboat,
  Sun, Moon, Cloud, Snowflake, Rainbow, Tornado, Thermometer, Umbrella, Waves, Wind, FlameKindling, Leaf, Sprout, Flower2, Trees, TreeDeciduous, Wheat,
  Dog, Cat, Bird, Fish, Rabbit, Squirrel, Turtle, Snail, Bug,
  Coffee, Beer, Wine, UtensilsCrossed, Utensils, Pizza, Apple, Banana, Cherry, Grape,
  Stethoscope, Pill, Hospital, Activity,
  Coins, DollarSign, TrendingUp, ShoppingBag, ShoppingCart, Package, Store, Gem,
  Hammer, Wrench, Scissors, Ruler, PaintBucket, Dumbbell,
  Mail, Phone, Radio, Newspaper, Megaphone, Bell, BellRing, Siren,
  Circle, Square, Triangle, Diamond, Pentagon, Octagon, Hash, Percent, Eye, Search, Info, HelpCircle, AlertTriangle,
} from "lucide-react";

export const ICON_CATEGORIES = [
  {
    label: "People & Emotions",
    icons: [
      { name: "User", component: User },
      { name: "Users", component: Users },
      { name: "Baby", component: Baby },
      { name: "Crown", component: Crown },
      { name: "UserCheck", component: UserCheck },
      { name: "PersonStanding", component: PersonStanding },
      { name: "Footprints", component: Footprints },
      { name: "Laugh", component: Laugh },
      { name: "Smile", component: Smile },
      { name: "Frown", component: Frown },
      { name: "Meh", component: Meh },
      { name: "Heart", component: Heart },
      { name: "HeartCrack", component: HeartCrack },
      { name: "HeartHandshake", component: HeartHandshake },
      { name: "ThumbsUp", component: ThumbsUp },
      { name: "ThumbsDown", component: ThumbsDown },
      { name: "HandMetal", component: HandMetal },
    ],
  },
  {
    label: "Places",
    icons: [
      { name: "MapPin", component: MapPin },
      { name: "Map", component: Map },
      { name: "Navigation", component: Navigation },
      { name: "Home", component: Home },
      { name: "Building2", component: Building2 },
      { name: "Castle", component: Castle },
      { name: "Hotel", component: Hotel },
      { name: "Factory", component: Factory },
      { name: "Globe", component: Globe },
      { name: "Globe2", component: Globe2 },
      { name: "Landmark", component: Landmark },
      { name: "Mountain", component: Mountain },
      { name: "TreePine", component: TreePine },
      { name: "Tent", component: Tent },
      { name: "Warehouse", component: Warehouse },
    ],
  },
  {
    label: "Time",
    icons: [
      { name: "Clock", component: Clock },
      { name: "Watch", component: Watch },
      { name: "Calendar", component: Calendar },
      { name: "CalendarDays", component: CalendarDays },
      { name: "CalendarClock", component: CalendarClock },
      { name: "Timer", component: Timer },
      { name: "Hourglass", component: Hourglass },
    ],
  },
  {
    label: "Events & Milestones",
    icons: [
      { name: "Star", component: Star },
      { name: "Sparkle", component: Sparkle },
      { name: "Sparkles", component: Sparkles },
      { name: "Flag", component: Flag },
      { name: "Bookmark", component: Bookmark },
      { name: "Trophy", component: Trophy },
      { name: "Award", component: Award },
      { name: "Medal", component: Medal },
      { name: "Ribbon", component: Ribbon },
      { name: "PartyPopper", component: PartyPopper },
      { name: "Zap", component: Zap },
      { name: "Flame", component: Flame },
    ],
  },
  {
    label: "Military & Politics",
    icons: [
      { name: "Swords", component: Swords },
      { name: "Sword", component: Sword },
      { name: "Shield", component: Shield },
      { name: "Bomb", component: Bomb },
      { name: "Target", component: Target },
      { name: "Crosshair", component: Crosshair },
      { name: "Skull", component: Skull },
      { name: "Anchor", component: Anchor },
      { name: "Vote", component: Vote },
      { name: "Scale", component: Scale },
      { name: "Gavel", component: Gavel },
      { name: "ScrollText", component: ScrollText },
      { name: "Stamp", component: Stamp },
      { name: "Handshake", component: Handshake },
      { name: "Lock", component: Lock },
      { name: "Unlock", component: Unlock },
      { name: "Key", component: Key },
      { name: "KeyRound", component: KeyRound },
    ],
  },
  {
    label: "Religion & Culture",
    icons: [
      { name: "Church", component: Church },
      { name: "Cross", component: Cross },
      { name: "Scroll", component: Scroll },
      { name: "BookOpen", component: BookOpen },
    ],
  },
  {
    label: "Science, Tech & Education",
    icons: [
      { name: "Atom", component: Atom },
      { name: "Microscope", component: Microscope },
      { name: "FlaskConical", component: FlaskConical },
      { name: "TestTube", component: TestTube },
      { name: "Dna", component: Dna },
      { name: "Telescope", component: Telescope },
      { name: "Compass", component: Compass },
      { name: "Cpu", component: Cpu },
      { name: "Lightbulb", component: Lightbulb },
      { name: "Sigma", component: Sigma },
      { name: "Pi", component: Pi },
      { name: "Infinity", component: InfinityIcon },
      { name: "Monitor", component: Monitor },
      { name: "Tv", component: Tv },
      { name: "Tv2", component: Tv2 },
      { name: "Smartphone", component: Smartphone },
      { name: "Laptop", component: Laptop },
      { name: "Keyboard", component: Keyboard },
      { name: "Mouse", component: Mouse },
      { name: "Wifi", component: Wifi },
      { name: "Bluetooth", component: Bluetooth },
      { name: "Signal", component: Signal },
      { name: "GraduationCap", component: GraduationCap },
      { name: "School", component: School },
      { name: "Library", component: Library },
      { name: "Pencil", component: Pencil },
    ],
  },
  {
    label: "Arts, Media & Gaming",
    icons: [
      { name: "Music", component: Music },
      { name: "Music2", component: Music2 },
      { name: "AudioLines", component: AudioLines },
      { name: "Headphones", component: Headphones },
      { name: "Mic", component: Mic },
      { name: "Mic2", component: Mic2 },
      { name: "Film", component: Film },
      { name: "Clapperboard", component: Clapperboard },
      { name: "Camera", component: Camera },
      { name: "Ticket", component: Ticket },
      { name: "Theater", component: Theater },
      { name: "Drama", component: Drama },
      { name: "Palette", component: Palette },
      { name: "Brush", component: Brush },
      { name: "PenLine", component: PenLine },
      { name: "Feather", component: Feather },
      { name: "Book", component: Book },
      { name: "BookMarked", component: BookMarked },
      { name: "FileText", component: FileText },
      { name: "Gamepad", component: Gamepad },
      { name: "Gamepad2", component: Gamepad2 },
      { name: "Joystick", component: Joystick },
      { name: "Dice1", component: Dice1 },
      { name: "Dice2", component: Dice2 },
      { name: "Dice3", component: Dice3 },
      { name: "Dice4", component: Dice4 },
      { name: "Dice5", component: Dice5 },
      { name: "Dice6", component: Dice6 },
    ],
  },
  {
    label: "Transport",
    icons: [
      { name: "Car", component: Car },
      { name: "Truck", component: Truck },
      { name: "Bus", component: Bus },
      { name: "Bike", component: Bike },
      { name: "Train", component: Train },
      { name: "Plane", component: Plane },
      { name: "Rocket", component: Rocket },
      { name: "Ship", component: Ship },
      { name: "Sailboat", component: Sailboat },
      { name: "Anchor", component: Anchor },
    ],
  },
  {
    label: "Nature & Animals",
    icons: [
      { name: "Sun", component: Sun },
      { name: "Moon", component: Moon },
      { name: "Cloud", component: Cloud },
      { name: "Snowflake", component: Snowflake },
      { name: "Rainbow", component: Rainbow },
      { name: "Tornado", component: Tornado },
      { name: "Thermometer", component: Thermometer },
      { name: "Umbrella", component: Umbrella },
      { name: "Waves", component: Waves },
      { name: "Wind", component: Wind },
      { name: "FlameKindling", component: FlameKindling },
      { name: "Leaf", component: Leaf },
      { name: "Sprout", component: Sprout },
      { name: "Flower2", component: Flower2 },
      { name: "Trees", component: Trees },
      { name: "TreeDeciduous", component: TreeDeciduous },
      { name: "Wheat", component: Wheat },
      { name: "Dog", component: Dog },
      { name: "Cat", component: Cat },
      { name: "Bird", component: Bird },
      { name: "Fish", component: Fish },
      { name: "Rabbit", component: Rabbit },
      { name: "Squirrel", component: Squirrel },
      { name: "Turtle", component: Turtle },
      { name: "Snail", component: Snail },
      { name: "Bug", component: Bug },
    ],
  },
  {
    label: "Food, Health & Commerce",
    icons: [
      { name: "Coffee", component: Coffee },
      { name: "Beer", component: Beer },
      { name: "Wine", component: Wine },
      { name: "UtensilsCrossed", component: UtensilsCrossed },
      { name: "Utensils", component: Utensils },
      { name: "Pizza", component: Pizza },
      { name: "Apple", component: Apple },
      { name: "Banana", component: Banana },
      { name: "Cherry", component: Cherry },
      { name: "Grape", component: Grape },
      { name: "Stethoscope", component: Stethoscope },
      { name: "Pill", component: Pill },
      { name: "Hospital", component: Hospital },
      { name: "Activity", component: Activity },
      { name: "Coins", component: Coins },
      { name: "DollarSign", component: DollarSign },
      { name: "TrendingUp", component: TrendingUp },
      { name: "ShoppingBag", component: ShoppingBag },
      { name: "ShoppingCart", component: ShoppingCart },
      { name: "Package", component: Package },
      { name: "Store", component: Store },
      { name: "Gem", component: Gem },
    ],
  },
  {
    label: "Tools & Communication",
    icons: [
      { name: "Hammer", component: Hammer },
      { name: "Wrench", component: Wrench },
      { name: "Scissors", component: Scissors },
      { name: "Ruler", component: Ruler },
      { name: "PaintBucket", component: PaintBucket },
      { name: "Dumbbell", component: Dumbbell },
      { name: "Mail", component: Mail },
      { name: "Phone", component: Phone },
      { name: "Radio", component: Radio },
      { name: "Newspaper", component: Newspaper },
      { name: "Megaphone", component: Megaphone },
      { name: "Bell", component: Bell },
      { name: "BellRing", component: BellRing },
      { name: "Siren", component: Siren },
    ],
  },
  {
    label: "Symbols",
    icons: [
      { name: "Circle", component: Circle },
      { name: "Square", component: Square },
      { name: "Triangle", component: Triangle },
      { name: "Diamond", component: Diamond },
      { name: "Pentagon", component: Pentagon },
      { name: "Octagon", component: Octagon },
      { name: "Hash", component: Hash },
      { name: "Percent", component: Percent },
      { name: "Eye", component: Eye },
      { name: "Search", component: Search },
      { name: "Info", component: Info },
      { name: "HelpCircle", component: HelpCircle },
      { name: "AlertTriangle", component: AlertTriangle },
    ],
  },
];

export const ICON_MAP = Object.fromEntries(
  ICON_CATEGORIES.flatMap((cat) => cat.icons.map(({ name, component }) => [name, component]))
);

export const ALL_ICONS = ICON_CATEGORIES.flatMap((cat) => cat.icons);
